defmodule AtelierWeb.Components.Button do
  use AtelierWeb, :live_component

  @moduledoc """
  Generated by Atelier
  """

  @metadata %{
    name: "Button",
    updated_at: "2026-03-04T20:24:33.598368Z"
  }

  attr :type, :string, default: "button"
  attr :disabled, :boolean, default: false
  attr :class, :string, default: ""
  attr :icon, :atom, default: nil
  attr :rest, :global

  slot :inner_block, required: true

  def button(assigns) do
    ~H"""
    <button
      type={@type}
      disabled={@disabled}
      class={["btn", @class]}
      {@rest}
    >
      <.icon :if={@icon} name={@icon} class="size-5" />
      {render_slot(@inner_block)}
    </button>
    """
  end

  def html do
    "<button\n  type=\"button\"\n  class=\"btn\"\n>\n  Button\n</button>"
  end

  def jsx(assigns) do
    ~H"""
    <script :type={Phoenix.LiveView.ColocatedJS} name="Button" extension="jsx">
        export default function Button({
      type = "button",
      disabled = false,
      className = "",
      icon: Icon = null,
      children,
      ...rest
      }) {
      return (
      <button
        type={type}
        disabled={disabled}
        className={`btn ${className}`}
        {...rest}
      >
        {Icon && <Icon className="size-5" />}
        {children}
      </button>
      );
      }
    </script>
    """
  end

  def metadata, do: @metadata
end
