defmodule AtelierWeb.Components.Button do
  use AtelierWeb, :live_component

  @moduledoc """
  Generated by Atelier
  """

  @atelier %{
    name: "Button",
    html:
      "<button\n  type=\"button\"\n  class=\"btn btn-warning\"\n  onclick=\"alert('This is an alert')\"\n>\n  <span class=\"hero-exclamation-triangle h-6 w-6 mr-1\"></span>\n  Alert\n</button>",
    prompt: "Looks good, let's make the icon smaller",
    model: "claude-sonnet-4-6",
    updated_at: "2026-03-04T18:00:11.684658Z"
  }

  attr :label, :string, default: "Alert"
  attr :message, :string, default: "This is an alert"
  attr :class, :string, default: ""
  attr :rest, :global

  def alert_button(assigns) do
    ~H"""
    <button
      type="button"
      class={["btn btn-warning", @class]}
      onclick={"alert('#{@message}')"}
      {@rest}
    >
      <.icon name="hero-exclamation-triangle" class="h-6 w-6 mr-1" />
      {@label}
    </button>
    """
  end

  def __atelier__, do: @atelier
end
